Milestone_3/milestone3/milestone3/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace milestone3.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

Milestone_3/milestone3/milestone3/Controllers/TopicsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using milestone3.Models;

namespace milestone3.Controllers
{
    public class TopicsController : Controller
    {
        private ToasterItContext db = new ToasterItContext();

        // GET: Topics
        public ActionResult Index()
        {
            var topics = db.Topics.OrderByDescending(t => t.Timestamp);
            return View(topics.ToList());
        }

        // GET: Topics/Create
        public ActionResult Create()
        {
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "CategoryName");
            return View();
        }

        // POST: Topics/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TopicId,Title,WebURL,Ranking,Views,Timestamp,CategoryID")] Topic topic)
        {
            if (ModelState.IsValid)
            {
                db.Topics.Add(topic);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "CategoryName", topic.CategoryID);
            return View(topic);
        }

        // GET: Topics/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Topic topic = db.Topics.Find(id);
            if (topic == null)
            {
                return HttpNotFound();
            }
            
            return View(topic);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Milestone_3/milestone3/milestone3/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ToasterIt</h1>
    For informed users who need more information on a topic from multiple view points, ToasterIt is a central discussion site for users so that they can civilly discuss any topic and pose questions related to those topics. This site will provide a forum for users to discuss topics from other sites that do not host discussion forums such as CNN. Unlike the news sites that host these articles, users can have discussion and debate about these topics from multiple news sources. Our product will allow users to view articles from multiple sites to allow users to get the full story and perspective on a particular topic.
</div>



<div class="row">
    <div class="col-md-12">
        <center>
            <h2>Browse Posts!</h2>
            @*need to work on the topic page, once we got the database working*@
            <p><a class="btn btn-primary" @Html.ActionLink("Read", "Index", "Topics")</a></p>

            <table>
                @{ /* ----- NOTE: replace DATABASENAME with Azure database -----*/

                <tbody>
                    @*@foreach (var item in Model)*@
                    @*{*@
                    <tr>
                        <td>
                            @* @Html.DisplayFor(m => DATABASENAME.ID) *@
                        </td>
                    </tr>
                    @*}*@
                </tbody>
                        /*  ----- NOTE: replace DATABASENAME with Azure database -----*/

                <tbody>
                    @*@foreach (var item in Model)*@
                    @*{*@
                    <tr>
                        <td>
                            @* @Html.DisplayFor(m => DATABASENAME.ID) *@
                        </td>
                        <td>



                            @* @Html.DisplayFor(m => DATABASENAME.Title) *@
                        </td>
                        <td>
                            @* @Html.DisplayFor(m => DATABASENAME.Ranking) *@
                        </td>
                        <td>
                            @* @Html.DisplayFor(m => DATABASENAME.Views) *@
                        </td>
                        <td>
                            @* @Html.DisplayFor(m => DATABASENAME.Category) *@
                        </td>

                        <td>

                            @*check for date*@
                            @*@if (Timestamp.Date == DateTime.Today)
                {
                    @*Format DateTime to show only the time
                    DateTime time = item.Timestamp;
                    @time.ToString("hh:mm tt");
                }
                else
                {
                    @Html.DisplayFor(m => item.Timestamp)
                }*@

                        </td>
                    </tr>
                    @*}*@
                </tbody>
                        }
             </table>
            <h2 style="padding-top:50px;">Create a New Post!</h2>
            @*need to work on the topic page, once we got the database working*@
            <p><a class="btn btn-primary" @Html.ActionLink("Create", "Create", "Topics")</a></p>

        </center>
    </div>
</div>