Milestone_3/milestone3/milestone3/Models/Topic.cs
namespace milestone3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Topic
    {
        public int TopicId { get; set; }

        [Required]
        [StringLength(50)]
        public string Title { get; set; }

        [Required]
        [StringLength(500)]
        public string WebURL { get; set; }

        public int Rank = 0;
        public int Ranking
        {
            get { return Rank; }
            set { Rank = value; }
        }

        public int View = 0;
        public int Views
        {
            get { return View; }
            set { View = value; }
        }

        public DateTime Date = DateTime.Now;

        public DateTime Timestamp
        {
            get { return Date; }
            set { Date = value; }
        }

        public int CategoryID { get; set; }

        public virtual Category Category { get; set; }
    }
}

Milestone_3/milestone3/milestone3/Controllers/CommentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using milestone3.Models;
using System.Diagnostics;

namespace milestone3.Controllers
{
    public class CommentsController : Controller
    {
        private ToasterItContext db = new ToasterItContext();

        // GET: Comments with ID
        public ActionResult Index(int id)
        {
            // Get the title of the page of the comments we are looking at
            var title = db.Topics.Where(x => x.TopicId == id).SingleOrDefault()?.Title;
            ViewBag.Title = title;
            // Store the id for the page
            ViewBag.Topic = id;
            // Return only comments from current post (this will have to be fixed if we add navigation to just comments
            return View(db.Comments.Where(i => i.TopicId.Value == id).ToList());
        }

        // GET: Comments/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.Comments.Find(id);
            //For use of return button in details page
            ViewBag.Topic = comment.TopicId;
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        // GET: Comments/Create
        // Make sure to pass in topicid or this baby will break the site now
        public ActionResult Create(int? topicid)
        {
            ViewBag.Topic = topicid;
            Comment comment = new Comment
            {
                TopicId = topicid
            };
            return View(comment);
        }

        // POST: Comments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CommentId,Content,Ranking,TopicId")] Comment comment)
        {
            //Viewbag is a blessing, we can return with it
            ViewBag.Topic = comment.TopicId;

            if (ModelState.IsValid)
            {
                comment.Timestamp = DateTime.Now;
                // User defaultly upvotes their own post
                comment.Ranking = 1;
                db.Comments.Add(comment);
                db.SaveChanges();
                //Make sure we are redirected to comments with appropriate id
                return RedirectToAction("Index", new { id = ViewBag.Topic });
            }

            return View(comment);
        }

        // GET: Comments/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        // POST: Comments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CommentId,Content,Ranking,Timestamp,TopicId")] Comment comment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(comment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(comment);
        }

        // GET: Comments/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        // POST: Comments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Comment comment = db.Comments.Find(id);
            db.Comments.Remove(comment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Milestone_3/milestone3/milestone3/Controllers/TopicsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using milestone3.Models;

namespace milestone3.Controllers
{
    public class TopicsController : Controller
    {
        private ToasterItContext db = new ToasterItContext();

        // GET: Topics
        public ActionResult Index()
        {
            var topics = db.Topics.OrderByDescending(t => t.Timestamp);
            return View(topics.ToList());
        }

        // GET: Topics/Create
        public ActionResult Create()
        {
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "CategoryName");
            return View();
        }

        // POST: Topics/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TopicId,Title,WebURL,Ranking,Views,Timestamp,CategoryID")] Topic topic)
        {
            if (ModelState.IsValid)
            {
                db.Topics.Add(topic);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "CategoryName", topic.CategoryID);
            return View(topic);
        }

        // GET: Topics/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Topic topic = db.Topics.Find(id);
            if (topic == null)
            {
                return HttpNotFound();
            }
            
            return View(topic);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Milestone_3/milestone3/milestone3/Views/Topics/Create.cshtml
@model milestone3.Models.Topic

@{
    ViewBag.Title = "Create";
}

<h2>Create a New Post</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, "Post Title", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WebURL, "Website Link", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WebURL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.WebURL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryID, "Category", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Posts", "Index")
</div>

Milestone_3/milestone3/milestone3/Views/Topics/Details.cshtml
@model milestone3.Models.Topic

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Topic</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Category.CategoryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.CategoryName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WebURL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WebURL)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ranking)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ranking)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Views)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Views)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Timestamp)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Timestamp)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Comment", "Create", "Comments", new { topicid = Model.TopicId }, null) |
    @Html.ActionLink("Back to List", "Index")
</p>

Milestone_3/milestone3/milestone3/Views/Topics/Index.cshtml
@model IEnumerable<milestone3.Models.Topic>

@{
    ViewBag.Title = "Index";
}

<h2>All Posts</h2>

<p>
    @Html.ActionLink("Create a New Post!", "Create")
</p>
<table class="table">
    <tr>
        <th>
            Upvotes
        </th>
        <th>
            News Title
        </th>
        <th>
            Category
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Views)
        </th>
        <th>
            Time Posted
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Ranking)
        </td>
        <td>
            <a href="@Html.DisplayFor(modelItem => item.WebURL)">@Html.DisplayFor(modelItem => item.Title)</a>
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Category.CategoryName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Views)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Timestamp)
        </td>
        <td>
            @Html.ActionLink("Details", "Details", new { id=item.TopicId })
        </td>
        <td>
            @Html.ActionLink("Comments", "Index", "Comments", new { id = item.TopicId }, null)
        </td>
    </tr>
}

</table>